project:
  type: website
  output-dir: docs

website:
  title: "EMCHD 2026"
  favicon: images/250812-155445.avif
  site-url: https://emchd2026.org/
  # announcement:
  #   icon: info-circle
  #   dismissable: true
  # content: "**Alert** - This Website is under construction"
  # type: primary
  # position: below-navbar
  navbar:
    logo: images/250812-155445.avif
    left:
      - href: index.qmd
        text: Home
      - href: content/programme.qmd
        text: Programme
      - href: content/travel.qmd
        text: Travel
      - href: content/accommodation.qmd
        text: Accommodation
      - href: content/venue.qmd
        text: Venue & Locations
      - href: content/ecr-events.qmd
        text: ECR Events
      - href: content/sponsor.qmd
        text: Sponsors
      - href: content/awards.qmd
        text: Awards
      - href: content/committee.qmd
        text: Organising Committee
    right:
      - icon: github
        href: https://github.com/H-Mateus/emchd-2026-website
  page-footer:
    left: "Content is licensed under the [GPL 3.0
      License](https://www.gnu.org/licenses/gpl-3.0.en.html)"
    center: "Made by [Mateus Harrington](https://mateusharrington.com) with
      [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/H-Mateus/emchd-2026-website

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left
