project:
  type: website
  output-dir: docs

website:
  title: "EMCHD 2026"
  site-url: https://emchd2026.org/
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This Website is under construction"
    type: primary
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/H-Mateus/emchd-2026-website
  page-footer: 
    left: "Content is licensed under the [GPL 3.0 License](https://www.gnu.org/licenses/gpl-3.0.en.html)"
    center: "Made by [Mateus Harrington](https://mateusharrington.com) with [Quarto](https://quarto.org)"
    right: 
      - icon: github
        href: https://github.com/H-Mateus/emchd-2026-website

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



