project:
  type: website
  output-dir: docs

website:
  title: "EMCHD 2026"
  site-url: https://emchd2026.org/
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This Website is under construction"
    type: primary
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



