---
title: "Accomodation"
---

Cardiff offers a wide range of hotels from budget to 4-star available in the city centre, all within 10-15min walking distance of the main conference venue (CSL).

You can book your stay directly from the relevant websites. We recommend booking early as hotel rooms can become scarce and more expensive in the summer/autumn months with many major concerts and events happening in the city. 

To provide a budget-friendly option we will be able to offer some limited accommodation at Cardiff University halls of residences; details will be announced in early 2026. 

## List of local hotels:

1. Park Inn by Radisson Hotel, Cardiff City Centre (4 star)  
Mary Ann Street, Cardiff CF10 2JH, tel. 029 2034 1441  
[https://www.radissonhotels.com/en-us/hotels/park-inn-cardiff-city-centre](https://www.radissonhotels.com/en-us/hotels/park-inn-cardiff-city-centre)  
1. Park Plaza (4 star)  
Greyfriars Road, Cardiff, CF10 3AL, tel.44 (0) 2920 111 111  
Park Plaza Cardiff - An award winning deluxe hotel in Cardiff  
1. Clayton Hotel (4 star)  
Penarth Rd, Cardiff CF10 1RH, tel. 029 2066 8866  
[https://www.claytonhotelcardiff.com](https://www.claytonhotelcardiff.com)  
1. Novotel Cardiff Centre (4 star)  
Schooner Way, Atlantic Wharf, Cardiff CF10 4RT, tel. 029 2047 5053  
[https://all.accor.com/hotel/5982/index.en.shtml](https://all.accor.com/hotel/5982/index.en.shtml)  
1. Radisson Blu Hotel, Cardiff (4 star)  
Meridian Gate, Bute Terrace, Cardiff CF10 2FL, tel. 029 2045 4777  
[https://www.radissonhotels.com/en-us/hotels/radisson-blu-cardiff](https://www.radissonhotels.com/en-us/hotels/radisson-blu-cardiff)  
1. Leonardo Hotel (3 star; formerly Jury’s Inn)  
1 Park Place, CF10 3DN), tel. 0161 774 2983  
[https://www.leonardo-hotels.com/cardiff/leonardo-hotel-cardiff](https://www.leonardo-hotels.com/cardiff/leonardo-hotel-cardiff)  
1. The Angel Hotel (3 star)  
Castle Street, Cardiff, Wales, CF10 1SZ, United Kingdom, tel. 029 2064 9200  
Home | The Angel Hotel ([angelhotelcardiffcity.co.uk](angelhotelcardiffcity.co.uk))  
1. Holiday Inn, Cardiff City Centre (3 star)  
Castle Street, Cardiff, CF10 1XD, tel. 0371 942 9240  
[https://www.ihg.com/holidayinn/hotels/gb/en/cardiff/cdfcy/hoteldetail  ](https://www.ihg.com/holidayinn/hotels/gb/en/cardiff/cdfcy/hoteldetail)  
1. Ibis Budget Hotel Cardiff (2 star)  
Tyndall St, Cardiff CF10 4BE, tel. 029 2045 8131  
[https://all.accor.com/hotel/6175/index.en.shtml](https://all.accor.com/hotel/6175/index.en.shtml)  
1. Urban Space Park Lake Aparthotel  
Offers Studios and 1 bedroom apartments  
23-24 Park Place, Cardiff, CF10 3BA, tel. 02920 029 959  
[www.theurbanspace.co.uk ](www.theurbanspace.co.uk)


