---
title: "Conference Programme"
# page-layout: full
---

# Conference Programme

The programme below is provisional and subject to change.

### Pre-Conference Events

Before the main meeting begins on Day 1, attendees have the opportunity to join one of our two parallel pre-conference tracks: the Training Day or the Complement in the Brain Symposium.  
Please check the schedule below for specific timings before the main meeting convenes.

::: {.panel-tabset}

## Training Day - 1 Sept

| Time | Event |
|---|---|
| 8:30 | Registration |
| 9:00-9:25 | Welcome – Elena Goicoechea de Jorge |
| 9:30-10:15 | **Parallel Sessions 1** <br><br> **Session 1:** Introduction to complement – *Sarah Carpanini* <br> **Session 2:** Complement – Past, Present and Future – *Richard Harrison* <br> **Session 3:** Complement structural biology – *Jean Van Den Elsen* |
| 10:15-10:40 | Coffee Break |
| 10:40-11:25 | **Parallel Sessions 2** <br><br> **Session 1:** Complement and Cancer – *Silvia Guglietta* <br> **Session 2:** Complement in Infectious Disease – *Suzan Rooijakkers* <br> **Session 3:** Complement and Autoimmunity – *Felix Poppelaars* |
| 11:25-11:30 | Comfort break |
| 11:30-12:15 | **Parallel Sessions 3** <br><br> **Session 1:** Complement Therapeutics – *Claire Harris* <br> **Session 2:** Non-canonical Roles of Complement – *Lubka Roumenina* <br> **Session 3:** Complement Genetics - *Hector Merinero* |
| 12:15-13:15 | Lunch |
| 13:15-14:05 | **Careers in Research and Beyond Panel** <br><br> **Chair:** Lewis Watkins <br> Khalil Mallah - Newly Established PI <br> Megan Torvell - Teaching <br> Lana Evans – Lab management <br> Samuel Butler – Industry rep (Svar) <br> Andy Robertson – Biotech Sales (VWR) |
| 14:05-14:10 | Comfort break |
| 14:10-15:00 | **Complement Methods Panel** <br><br> **Chair:** Kevin Marchbank <br> Protein purification – Nicole Schäfer <br> Haemolytic assays – Robert Byrne <br> ELISAs - Nikoleta Daskoulidou <br> SPR – Kok Yung Lee <br> Complement Animal Models – Kevin Marchbank |
| 15:00-15:25 | Coffee Break |
| 15:25-16:25 | **Intracellular Complement Debate** <br><br> *"What actually is controversial in the subject of intracellular complement?"* <br><br> **Chair:** Jean Van Den Elsen <br> Ben King, Lubka Roumenina, Christoph Schmidt, Gregers Rom Andersen |
| 16:25 | Depart for Keynote address |

## Complement in the Brain Symposium Programme - 1 Sept

| Time  | Event |
|-------|-------|
| 8:30  | Registration Open |
| 9:00  | **Cynthia Lemere** – A Role for Complement in Anti-amyloid Antibody-induced Vascular Side Effects (ARIA) in Alzheimer's Disease |
| 9:30  | **Marcela Pekna** – C3aR in Stroke Recovery: Mechanisms and Clinical Implications |
| 10:00 | **Jan Lünemann** – Complement in Multiple Sclerosis and Related Disorders |
| 10:30 | **Markus Huber-Lang** – Role of Complement After Trauma in the Context of TBI |
| 11:00 | Flash Talks |
| 12:30 | Lunch and Poster Presentations |
| 13:30 | **Paul Morgan** – Targeting Complement in Neurodegeneration |
| 14:00 | **Valeria Ramaglia** – Complement in the Multiple Sclerosis Brain: Where and How |
| 14:30 | **Soyon Hong** – Activity-dependent Neuro-glia-immune Regulation at the Synapse |
| 15:00 | Talks for Selected Abstracts |
| 16:30 | Coffee Break |
| 17:00 | **Keynote Presentation: Baljit S. Khakh** – The Cells That Tile Your Brain: Astrocyte Function and Failures in Neural Circuits |
| 18:30 | **EMCHD 2026 Opening Ceremony:** Evening Drinks & Canapés |

## Day 1 - 2 Sept

| Time | Session |
|---|---|
| 08:00 | Registration opens |
| 09:00 | Keynote 1 |
| 10:00 | Coffee break |
| 10:30 | Session 1 |
| 12:00 | SVAR Awards x2 |
| 12:45 | Lunch |
| 13:45 | Session 2 |
| 15:15 | Coffee break |
| 15:45 | Session 3 |
| 17:15 | Poster session 1 |
| 18:45 | Free time |
| 20:00 | Speakers dinner |


## Day 2 - 3 Sept

| Time | Session |
|---|---|
| 08:50 | Announcements |
| 09:00 | Keynote 2 |
| 10:00 | Coffee break |
| 10:30 | Session 4 |
| 12:00 | ECN Medal talks x2 |
| 12:45 | Sponsor talks |
| 13:00 | Lunch |
| 13:45 | Session 5 |
| 15:15 | Lambris Training Award |
| 15:35 | Coffee break |
| 16:00 | Poster Session 2 |
| 17:30 | Networking Like a Boss |
| 18:30 | Free time |
| 19:30 | ECR Social / Delegate Social |


## Day 3 - 4 Sept

| Time | Session |
|---|---|
| 08:50 | Announcements |
| 09:00 | Keynote 3 |
| 10:00 | Coffee break |
| 10:30 | Session 6 |
| 12:00 | SVAR Talk |
| 12:15 | ECN General |
| 12:30 | Lunch |
| 13:30 | Innovation / Commercialisation |
| 13:30 | Session 7 |
| 15:00 | Social excursion |
| 18:00 | Free time |
| 20:00 | Conference dinner |

## Day 4 - 5 Sept

| Time | Session |
|---|---|
| 07:50 | ECN Board Meeting |
| 08:50 | Announcements |
| 09:00 | Session 8 |
| 10:30 | Coffee break |
| 11:00 | Intracellular Complement Review Statement |
| 11:25 | ECCO Journal Article Award Talk |
| 11:40 | Awards Ceremony |
| 12:00 | Future Meetings |
| 12:20 | Concluding remarks |
| 12:30 | Packed lunch and departure |
| 13:30 | End of meeting |

:::

